let ResponseMap = new Map()
ResponseMap.set('100', {error: 'Transaction was approved', translation: ''})
ResponseMap.set('200', {error: 'Transaction was declined by processor', translation: ''})
ResponseMap.set('201', {error: 'Do not honor', translation: ''})
ResponseMap.set('202', {error: 'Insufficient funds', translation: ''})
ResponseMap.set('203', {error: 'Over limit', translation: ''})
ResponseMap.set('204', {error: 'Transaction not allowed', translation: ''})
ResponseMap.set('220', {error: 'Incorrect payment information', translation: ''})
ResponseMap.set('221', {error: 'No such card issuer', translation: ''})
ResponseMap.set('222', {error: 'No card number on file with issuer', translation: ''})
ResponseMap.set('223', {error: 'Expired card', translation: ''})
ResponseMap.set('224', {error: 'Invalid expiration date', translation: ''})
ResponseMap.set('225', {error: 'Invalid card security code', translation: ''})
ResponseMap.set('226', {error: 'Invalid PIN', translation: ''})
ResponseMap.set('240', {error: 'Call issuer for further information', translation: ''})
ResponseMap.set('250', {error: 'Pick up card', translation: ''})
ResponseMap.set('251', {error: 'Lost card', translation: ''})
ResponseMap.set('252', {error: 'Stolen card', translation: ''})
ResponseMap.set('253', {error: 'Fraudulent card', translation: ''})
ResponseMap.set('260', {
    error: 'Declined with further instructions available. (See response text',
    translation: '',
})
ResponseMap.set('261', {error: 'Declined-Stop all recurring payments', translation: ''})
ResponseMap.set('262', {error: 'Declined-Stop this recurring program', translation: ''})
ResponseMap.set('263', {error: 'Declined-Update cardholder data available', translation: ''})
ResponseMap.set('264', {error: 'Declined-Retry in a few days', translation: ''})
ResponseMap.set('300', {error: 'Transaction was rejected by gateway', translation: ''})
ResponseMap.set('400', {error: 'Transaction error returned by processor', translation: ''})
ResponseMap.set('410', {error: 'Invalid merchant configuration', translation: ''})
ResponseMap.set('411', {error: 'Merchant account is inactive', translation: ''})
ResponseMap.set('420', {error: 'Communication error', translation: ''})
ResponseMap.set('421', {error: 'Communication error with issuer', translation: ''})
ResponseMap.set('430', {error: 'Duplicate transaction at processor', translation: ''})
ResponseMap.set('440', {error: 'Processor format error', translation: ''})
ResponseMap.set('441', {error: 'Invalid transaction information', translation: ''})
ResponseMap.set('460', {error: 'Processor feature not available', translation: ''})
ResponseMap.set('461', {error: 'Unsupported card type', translation: ''})

export {ResponseMap}
